### ISSUE TITLE
output file fail

### ISSUE THREAD

**Issue by jhaoheng** [aubm/postmanerator#18]
Postman(4.5.0) export v1 version
`postmanerator -output=./doc.html -collection=mycol.json`
and the file 
![2016-08-02 10 40 50](https://cloud.githubusercontent.com/assets/1822475/17332694/325470de-5902-11e6-9609-7f884914924b.png)

**Comment by aubm** [comment]
Hello,

Let me quote this phrase from the README.md file:

> the default theme will parse your collection folders to find requests. "Orphan" requests will simply not be available in the documentation.

Do you confirm you are using folders?
