### ISSUE TITLE
Is there any support for Markdown tables?

### ISSUE THREAD

**Issue by Wideshanks** [aubm/postmanerator#21]
In the generated output, I get the unrendered table:

```
| Constant | Definition | | ----------- | ------------------------------------------------------------------------------------- | | weekly | ... | | 
```

**Comment by aubm** [comment]
Hello, thanks for reporting this.

https://github.com/russross/blackfriday is used to render markdown contents.
The documentation says it does support markdown tables now but maybe the version used in the latest Postmanerator build did not.

I'll try to create a fresh build later with updated dependencies, and see if it works better.

**Comment by aubm** [comment]
Ok, this release should work: https://github.com/aubm/postmanerator/releases/tag/v0.6.0

That being said, the table you provided earlier does not seem to be parsed, but the one provided in the exemple [here](https://github.com/russross/blackfriday#extensions) was.

Let me know if it is good enough for you.

**Comment by Wideshanks** [comment]
:+1:

Works. Thanks.
