### ISSUE TITLE
Same name in different folders example error

### ISSUE THREAD

**Issue by zanaca** [aubm/postmanerator#23]
When you have 2 different folders having items with same name within it breaks the example navigation. 
```
- resource 1 folder
  - v1 endpoint
     |curl example|http example|
  - v2 endpoint
     |curl example|http example|

- resource 2 folder
  - v1 endpoint
     |curl example|http example|
  - v2 endpoint  
     |curl example|http example|
```

When you click  on **v2 endpoint** http example from **resource 2 folder** it is showed  in **resource 1 folder** > **v2 endpoint** > http example box

**Comment by aubm** [comment]
Hey I just published a update on the default theme, which should solve your problem.
To update the theme, use:

```
postmanerator themes delete default
postmanerator themes get default
```

Please reopen if the problem is still there :)
