### ISSUE TITLE
Adds support for collection V2 format

### ISSUE THREAD

**Issue by aubm** [aubm/postmanerator#28]

**Comment by bruno-lopes** [comment]
@aubm, this project is really awesome! But it would be very nice to have this feature implemented, because here we use nested folders to separate the concerns of our project. Thanks in advance!

**Comment by SeekerResource** [comment]
and how about v2.1 format

**Comment by aubm** [comment]
I plan on working on it soon. 
The thing is that I want to add more tests before in order to cover more potential regressions.
For the record: I have initiated the work here: https://github.com/aubm/postmanerator/commit/287025ee17c5adfb35071f89e5176968d56d1905

**Comment by ravikannankr** [comment]
Any updates on support for V2.0/2.1/ETA?

**Comment by aubm** [comment]
Hey, sorry for the long delay.

v0.9.0 has been released with support for collection v2.1.
It should work OK with the latest Postman exporting to 2.1.

Please provide feedback if you encounter any regressions.
Also note that support for collection v1 is dropped in v0.9.0.

**Comment by ravikannankr** [comment]
Thank you for fixing it. Will check and revert if there are any issues.
