### ISSUE TITLE
help required

### ISSUE THREAD

**Issue by neerajmahajan83** [aubm/postmanerator#32]
i placed folder inside D: drive .after that when i am running the command "postmanerator -output=D:\postmanerator\doc.html -collection=D:\postmanerator\Learn jwt.postman_collection.json" gives error  postmanerator  is not recognized as internal or external command

**Comment by aubm** [comment]
You need to add the directory in which you placed the Postmanerator binary to your PATH environment variable. See https://www.computerhope.com/issues/ch000549.htm.
