### ISSUE TITLE
Error: function "findRequest" not defined

### ISSUE THREAD

**Issue by mlapeyre3** [aubm/postmanerator#37]
Hi there,

I try to run postamnerator.exe on a simple Postman collection.

Command:
`postmanerator.exe -collection .\Test.postman_collection.json -output ./doc.html`

Output:
`Generating output... FAIL. template: index.tpl:76: function "findRequest" not defined`

The file (in Collection v1 format)
`{
	"id": "4057bcfb-3544-fb26-5394-e95830a73fa7",
	"name": "Test",
	"description": "",
	"order": [],
	"folders": [
		{
			"name": "Test Folder",
			"description": "",
			"collectionId": "4057bcfb-3544-fb26-5394-e95830a73fa7",
			"order": [
				"97344fd0-4575-d8d8-6193-d01aaa0c840b"
			],
			"owner": "879589",
			"folders_order": [],
			"id": "68214c4e-5140-9cec-21cc-0f1ec9103b03"
		}
	],
	"folders_order": [
		"68214c4e-5140-9cec-21cc-0f1ec9103b03"
	],
	"timestamp": 1505925551843,
	"owner": "879589",
	"public": false,
	"requests": [
		{
			"id": "97344fd0-4575-d8d8-6193-d01aaa0c840b",
			"headers": "Content-Type: application/json\n",
			"headerData": [
				{
					"key": "Content-Type",
					"value": "application/json",
					"description": "",
					"enabled": true
				}
			],
			"url": "http://www.google.fr",
			"queryParams": [],
			"pathVariables": {},
			"pathVariableData": [],
			"preRequestScript": null,
			"method": "GET",
			"collectionId": "4057bcfb-3544-fb26-5394-e95830a73fa7",
			"data": [],
			"dataMode": "raw",
			"name": "http://www.google.fr",
			"description": "",
			"descriptionFormat": "html",
			"time": 1505925598916,
			"version": 2,
			"responses": [],
			"tests": null,
			"currentHelper": "normal",
			"helperAttributes": {},
			"folder": "68214c4e-5140-9cec-21cc-0f1ec9103b03",
			"rawModeData": ""
		}
	]
}`

**Comment by aubm** [comment]
Hello, just to be sure, have tried with the latest versions of Postmanerator AND the default theme ?

**Comment by aubm** [comment]
Try updating Postmanerator with the latest build, and use `postmanerator themes delete default`.
Then try again.

**Comment by mlapeyre3** [comment]
```
postmanerator_windows_amd64.exe -collection .\Test.json -output ./doc.html
Theme 'default' not found, trying to download it...
Generating output... SUCCESS.
```

It works! Thank you :)
