### ISSUE TITLE
FAIL. template: index.tpl:40: function "findRequest" not defined

### ISSUE THREAD

**Issue by loretoparisi** [aubm/postmanerator#43]
I'm using the latest available binary and I was trying Postman v1.0, v2.0 and recommended v2.1 but I get always:

```
$ postmanerator_darwin_386 -theme="markdown" -collection=./aiapi.json -output=./aiapi.html
Generating output... FAIL. template: index.tpl:40: function "findRequest" not defined
```

**Comment by jqdurham** [comment]
Same result for me.

**Comment by leviwilsonestevez** [comment]
It does not have been attended this issue

**Comment by aubm** [comment]
You might be interested in https://github.com/aubm/postmanerator/issues/31#issuecomment-436225885

**Comment by loretoparisi** [comment]
I solved this then doing

```
./postmanerator themes delete default
```
and not using the `-theme` parameter then.
