### ISSUE TITLE
index.tpl:76: function "findRequest" not defined

### ISSUE THREAD

**Issue by dusann** [aubm/postmanerator#47]
I've downloaded the latest windows exe file but when I try to run it throws this error:

> Generating output... [31mFAIL. template: index.tpl:76: function "findRequest" not defined[0m

Same result with another theme:

> Generating output... [31mFAIL. template: index.tpl:40: function "findRequest" not defined[0m

I tried with all 3 postman collection versions (v1, v2, v2.1) but the same error appears

**Comment by GabrielDvt** [comment]
Same here :(

**Comment by leviwilsonestevez** [comment]
Why was closed this issue? I don't find the solution.
