### ISSUE TITLE
"Define API structures" & Subfolders are not shown up in the generated html file

### ISSUE THREAD

**Issue by srajkavithaa** [aubm/postmanerator#51]
I have this following code in one of the requests "Test" tab but not seen in the generated html and also, all the requests are arranged in alphabetical order instead of sub folders structure - please refer the image. Any help will be highly appreciated, thanks.
/*[[start postmanerator]]*/
function populateNewAPIStructures() {
    APIStructures['Blueprint'] = {
        name: 'Blueprint',
        description: 'Blueprints are the architectural guidelines to build things. Blueprints are designed to provide you with a framework that you can construct multiple data instances from',
        fields: [
            {name: 'NodeType', description: 'You can create different node types and assign the required fields into it', type: 'xxx'},
            {name: 'Edges', description: 'The links between the nodes', type: 'string'},
            {name: 'Fields', description: 'Different types of data., Textbox, number, Memo etc', type: 'xxx'}
        ]
    };
}
/*[[end postmanerator]]*/

![postmanerator_html](https://user-images.githubusercontent.com/7603599/52922173-ebb8cd00-3383-11e9-8a69-75818f96217d.png)

The postman collection looks like this:
![postmanerator_postman](https://user-images.githubusercontent.com/7603599/52922277-03448580-3385-11e9-809d-49e3742d2bef.png)

****NOTE***
As the postman did not included the "postmanerator" related scripts, i have manually updated them and it looks like in the JSON file.

"events": [
				{
					"listen": "test",
					"script": {
						"id": "44b78a2a-7373-42bc-8920-f0c361bc1391",
						"exec": [
							"pm.test(\"Status code is 200\", function () {",
							"    pm.response.to.have.status(200);",
							"});",
							"",
							"",
							"(pm.response.code===200 ? pm.test : pm.test.skip)(\"Response returned valid guid\", function () {",
							"   ",
							"        pm.expect(pm.response.text()).to.include(pm.environment.get(\"BlueprintId\"));",
							"        pm.environment.set('BlueprintData', pm.response.text());",
							"  ",
							"});",
							"",
							"",
**"/*[[start postmanerator]]*/",
"function populateNewAPIStructures() {",
	"var responseBody = JSON.parse(responses['default'].body);",
    "APIStructures['Blueprints'] = {",
        "name: 'Blueprint',",
        "description: 'Blueprints are the architectural guidelines to build things. Blueprints are designed to provide you with a framework that you can construct multiple data instances from',",
        "fields: [",
            "{name: 'Node Type', description: 'You can create different node types and assign the required fields into it', type: 'xxx'},",
            "{name: 'Edges', description: 'The links between the nodes', type: 'string'},",
            "{name: 'Fields', description: 'Different types of data., Textbox, number, Memo etc', type: 'xxx'}",
        "]",
    "};",
"}",
"/*[[end postmanerator]]*/",**
"",
""
						], 

I am using Postman version # 6.7.3 and Windows 10 pro in my system.

**Comment by aubm** [comment]
Hello, Postman seems to have changed the way requests tests are exported in the collection v1.
As a result the parser that searches for your API structures definitions doesn't search at the right location.

As I was still going to implement support for [collection v2 eventually](https://github.com/aubm/postmanerator/issues/28), this issue would be addressed in the same time.
That being said, my original plan was to offer support for both v1 and v2. But as Postman doesn't seem to guarantee backward compatibility (at least for v1), maybe I will completely drop support for v1...

**Comment by srajkavithaa** [comment]
Thanks for the update, and hope we will get the updated Postmanerator soon!

**Comment by bux23** [comment]
Any updates on how to solve the issue while v2 support begin developed? Postmanerator is really really useful and this fuature is essential!

**Comment by aubm** [comment]
Hey, sorry for the long delay.

v0.9.0 has been released with support for collection v2.1.
It should work OK with the latest Postman exporting to 2.1.

Please provide feedback if you encounter any regressions.
Also note that support for collection v1 is dropped in v0.9.0.

**Comment by bux23** [comment]
Thank you!!
The generation from 2.1 export works fine, but when integrating the following in code  in test pane, no output for it is generated.

/*[[start postmanerator]]*/
function populateNewAPIStructures() {
    APIStructures['cat'] = {
        name: 'Cat',
        description: 'A great animal',
        fields: [
            {name: 'id', description: 'A unique identifier for the cat', type: 'int'},
            {name: 'color', description: 'The color of the cat', type: 'string'},
            {name: 'name', description: 'The name of the cat', type: 'string'}
        ]
    };
}
/*[[end postmanerator]]*/

**Comment by aubm** [comment]
That's weird, are you sure you are using the latest version of Postman with 0.9.0 of Postmanerator?

**Comment by bux23** [comment]
Yes. Postman v6.7.4 and 0.9.0 Postmanerator. Precisely the sinppet s inserted in the test pane of a POST request in a subdirectory of the exported collection.

**Comment by aubm** [comment]
I’m not entirely sure but your Postman might be outdated. I think 7.x has been released recently, you mat want to double check that.

**Comment by bux23** [comment]
Works with latest 7x version of Portman. Thank you very much @aubm !

**Comment by srajkavithaa** [comment]
Hi Aubm, thanks for the fix.
But this time I can see the first level folder structure as it is and no sub folders, no request details etc just seeing the first level information only. I am using Postman v7.0.9

![image](https://user-images.githubusercontent.com/7603599/57428515-dc5b6880-727c-11e9-8c83-e4dc57455c10.png)

Please help.

**Comment by MakDon** [comment]
Thanks for the update.
Subfolders are not shown up +1

**Comment by aubm** [comment]
Hello, the issue with the requests description is fixed in master.
Will create a new release soon.

**Comment by aubm** [comment]
About the subfolders thing, this is a limitation that the default theme has right now.

The main template is available [here](https://github.com/aubm/postmanerator-default-theme/blob/master/index.tpl).

I do not have much time right now unfortunately, but please feel free to fork it.
Contributions are also welcome!
