### ISSUE TITLE
Failed to parse collection file: invalid character 'p' after object key:value pair

### ISSUE THREAD

**Issue by evasyuk** [aubm/postmanerator#58]
I have a problem with docs generation

OS X Mojave 10.14.3
Build version 0.9.0
Build link https://github.com/aubm/postmanerator/releases/download/v0.9.0/postmanerator_darwin_amd64 

Postman collection version 2.1

Can send you collection as private message(if its required)

postmanerator failed
while newma-cli works fine

**Comment by aubm** [comment]
Hello @evasyuk, are you still having the issue?
If so a collection sample might help indeed.
Also please make sure that you are using the latest Postman release.

**Comment by evasyuk** [comment]
@aubm tried version 0.10.0. Now works fine!
Thank you very much!
