### ISSUE TITLE
Not parsing descriptions of request. 

### ISSUE THREAD

**Issue by qinwang717** [aubm/postmanerator#59]
I have version v0.9.0,  and postman collection.json v.2.1. 
I am able to generate the html file, and the description of the folder is generated correctly. 
However, the description for each requests are not generated on the html. 

Using the same text, copy and paste from the folder's description into the request's description, I still can not see the description generated for each requests, only for folders. Only the name of the request are shown, following by curl/http code. 

add: I can see the "description" field in my json file under each request node, so the descriptions are exported indeed. Also I can see them formatted and displayed correctly on Postman.

Any idea?

**Comment by aubm** [comment]
Hello @qinwang717  thank you for the notice.

I'm on it.

**Comment by aubm** [comment]
https://github.com/aubm/postmanerator/releases/tag/v0.10.0 is available :)
