### ISSUE TITLE
Provide an environnement file

### ISSUE THREAD

**Issue by aubm** [aubm/postmanerator#6]
Currently, postmanerator doesn't know about environnement variables when generating the documentation. That leads to (for example), curl snippets like the one below:

```
curl -X GET "http://{{domain}}/api/cats"
```

The postman UI provides a way to export an environnement in a JSON format. One should be able to provide this exported file, in completing of the collection file, in order to have to generate a rendering like the following:

```
curl -X GET "http://my-awesome.com/api/cats"
```

The environnement should be provided as a command line argument:

```
postmanerator -output="doc.html" -theme="my/theme/location" -environnement="env.json" collection.json
```

**Comment by jayanthakgjls** [comment]
Any update on this ?

**Comment by aubm** [comment]
Hello, unfortunately no yet.
I'll try to take into account your interest for this particular feature, and give you a heads-up when it is ready :)
