### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by ibubenko** [aubm/postmanerator#60]
After I run: go get github.com/aubm/postmanerator

I get the next message:
github.com/aubm/postmanerator/postman
../go/src/github.com/aubm/postmanerator/postman/collection_v210_parser.go:49:28: multiple-value uuid.NewV4() in single-value context
../go/src/github.com/aubm/postmanerator/postman/collection_v210_parser.go:59:30: multiple-value uuid.NewV4() in single-value context
../go/src/github.com/aubm/postmanerator/postman/collection_v210_parser.go:149:26: multiple-value uuid.NewV4() in single-value context

---
running:
go version go1.12.5 darwin/amd64

**Comment by aubm** [comment]
Hello @ibubenko, please make sure you are correctly using go modules in order to build the code.

It sounds like you are accidentally trying to build with the master version of https://github.com/satori/go.uuid although the `go.sum` should download `v1.2.0`.
